---
- name: Create systemd overrides directory for glusterd
  ansible.builtin.file:
    path: /etc/systemd/system/glusterd.service.d/
    state: directory

- name: Create glusterd cgroups CPU configuration file
  ansible.builtin.copy:
    src: 99-cpu.conf
    dest: /etc/systemd/system/glusterd.service.d/99-cpu.conf
    mode: preserve
  notify:
    - Restart glusterd

- name: Set CPU quota
  ansible.builtin.template:
    src: glusterfs.slice.j2
    dest: /etc/systemd/system/glusterfs.slice
  vars:
    gluster_cgroup_cpu_quota: "{{ [(ansible_processor_vcpus /3)|int, 1] | max * 100 }}"
  notify:
    - Restart glusterd

- name: Disable unrelated gluster hooks
  ansible.builtin.script: disable-gluster-hooks.sh
