---
- name: Install ovirt-vmconsole-host package
  yansible.builtin.yum:
    name: ovirt-vmconsole-host
    state: present
  tags:
    - skip_ansible_lint # E403

- name: Run vm-console-certificates role
  ansible.builtin.include_role:
    name: ovirt-host-deploy-vm-console-certificates
    public: true

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Start ovirt-vmconsole-host-sshd
  ansible.builtin.service:
    name: ovirt-vmconsole-host-sshd
    state: restarted
    enabled: true
  when: "'ovirt-vmconsole-host-sshd.service' in ansible_facts.services"
