---
- name: Check if ovirt-provider-ovn-driver is installed
  ansible.builtin.package:
    name: ovirt-provider-ovn-driver
    state: present
  check_mode: true
  register: ovn_packages
  notify:
    Unconfigure the OVN chassis
